### ISSUE TITLE
README - template for new section is disturbing

### ISSUE THREAD

**Issue by hartenthaler** [photon-flip/webtrees-HTML-block-compact#1]
in the README there is a block

```
 <div class="accord__item">
                <a class="accord__item__title" href="#item5">Add New Sections</a>
                <div class="accord__item__content" id="item5">
                    <h2>New Section Title</h2>
                    <hr>
                    <p>Content here</p>
                </div>
            </div>
            
/*add new sections before the three closing divs*/
        </div>
    </div>
</div>
```

I would expect to see
```
 <div class="accord__item">
            <a class="accord__item__title" href="#item5">Add New Sections</a>
            <div class="accord__item__content" id="item5">
                    <h2>New Section Title</h2>
                    <hr>
                    <p>Content here</p>
            </div>
 </div>
```
            
Add new sections before the three closing divs at the end of the code
```
        </div>
    </div>
</div>
```

So to make it clearer
- make the indention more clear and write the `</div>` exactly under the opening `<div>`
- separate the code blocks; the first one is intended to be used for "copy and paste" and the second one is only for orientation

**Comment by photon-flip** [comment]
Thanks Hermann for your great input. 
Odd indentation came about from copying a section of the complete code but yes, "disturbing" here.
I'd like to display the three closing divs without the copy capability but GitHub seems determined to add that even if I use just tabs or blockquotes. But still better now I think.
I'm working on your other issue suggestions - many thanks.

**Comment by photon-flip** [comment]
Update complete.
