### ISSUE TITLE
wrong URL in accordion.phtml

### ISSUE THREAD

**Issue by hartenthaler** [photon-flip/webtrees-HTML-block-compact#10]
In the statistices element there is a URL: href="http://localhost/webtrees2/tree/pre-changes" which is not generally valid. Maybe it would be better to remove that link or make it clear that it is an example that should be adapted by the user.

**Comment by photon-flip** [comment]
[set up for route to tree url for view accordion.](https://github.com/photon-flip/webtrees-HTML-block-compact/commit/3023913f3dce6b5705eb5fc2120481864be34584)

**Comment by photon-flip** [comment]
[set up for route to tree url for view accordion.](https://github.com/photon-flip/webtrees-HTML-block-compact/commit/3023913f3dce6b5705eb5fc2120481864be34584)
